# The physical footprint of your robot [x, y] in meters
footprint: [[0.2, 0.15], [-0.2, 0.15], [-0.2, -0.15], [0.2, -0.15]]

# How far to stay away from obstacles
inflation_layer:
  inflation_radius: 0.3

# Tell it to listen to your Gazebo LiDAR
obstacle_layer:
  observation_sources: laser_scan_sensor pedsim_sim_sensor
  laser_scan_sensor: {sensor_frame: lidar_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  
  # The simulated pedestrians!
  pedsim_sim_sensor: {
    sensor_frame: odom, # Or base_link, depending on how pedsim is configured
    data_type: PointCloud, # Or PointCloud2
    topic: /pedsim_obstacle_sensor/point_cloud_local, 
    marking: true, 
    clearing: true,
    obstacle_range: 5.0,
    raytrace_range: 6.0
  }
